[project]
name = "marmoset-paper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "anndata>=0.10.9",
    "fastexcel>=0.13.0",
    "igraph>=0.11.8",
    "ipykernel>=6.29.5",
    "leidenalg>=0.10.2",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "polars>=1.26.0",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
]
